// Verifies generateProtocolBeta / generateProtocolGamma in VectorSwarm.js
// produce output matching perfect_swarm.py's generate_protocol_beta /
// generate_protocol_gamma, using the fixture pairs in
// fixture_protocol_beta_gamma.json (generated by
// generate_fixture_protocol_beta_gamma.py).
//
// Run: node tests/test_protocol_beta_gamma.js

import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { generateProtocolBeta, generateProtocolGamma } from '../web/swarm/VectorSwarm.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Same tolerance convention as the APF fixture test (fixture values are
// rounded to 6 decimals on the Python side).
const TOLERANCE = 1e-6;

function loadFixture() {
  const raw = readFileSync(join(__dirname, 'fixture_protocol_beta_gamma.json'), 'utf-8');
  return JSON.parse(raw);
}

function assertPointsClose(actual, expected, label) {
  if (actual.length !== expected.length) {
    throw new Error(`${label}: length mismatch — got ${actual.length}, expected ${expected.length}`);
  }
  for (let i = 0; i < expected.length; i++) {
    for (let axis = 0; axis < 3; axis++) {
      const a = actual[i][axis];
      const e = expected[i][axis];
      const diff = Math.abs(a - e);
      if (diff > TOLERANCE) {
        throw new Error(
          `${label}: point ${i}, axis ${axis} mismatch — got ${a}, expected ${e} (diff ${diff})`
        );
      }
    }
  }
}

function runBetaTests(fixture) {
  let passed = 0;
  for (const [name, { input, output: expected }] of Object.entries(fixture.protocol_beta)) {
    const actual = generateProtocolBeta(
      input.n_drones,
      input.start_point,
      input.end_point,
      input.altitude
    );
    assertPointsClose(actual, expected, `protocol_beta/${name}`);
    console.log(`  ok - protocol_beta/${name} (${actual.length} points)`);
    passed++;
  }
  return passed;
}

function runGammaTests(fixture) {
  let passed = 0;
  for (const [name, { input, output: expected }] of Object.entries(fixture.protocol_gamma)) {
    const actual = generateProtocolGamma(
      input.n_drones,
      input.center,
      input.radius,
      input.altitude
    );
    assertPointsClose(actual, expected, `protocol_gamma/${name}`);
    console.log(`  ok - protocol_gamma/${name} (${actual.length} points)`);
    passed++;
  }
  return passed;
}

function main() {
  const fixture = loadFixture();

  console.log('Protocol Beta:');
  const betaPassed = runBetaTests(fixture);

  console.log('Protocol Gamma:');
  const gammaPassed = runGammaTests(fixture);

  const total = betaPassed + gammaPassed;
  console.log(`\n${total} scenario(s) passed.`);
}

main();
